### ISSUE TITLE
Problem with plugins search filtering

### ISSUE THREAD

**Issue by Srokap** [Elgg/community_plugins#117]
I recently updated some of my plugins compatibility info to include 1.10, hovever, they don't show on a search results.

Have a look at: https://community.elgg.org/plugins/search?f%5Bv%5D%5B%5D=1.10&f%5Bt%5D=&sb=Search

I have currently 3 plugins marked as compatible:
- https://community.elgg.org/plugins/1307052
- https://community.elgg.org/plugins/1213751
- https://community.elgg.org/plugins/1158489

**Comment by Srokap** [comment]
Looks like they start to show up when I go to edit and save them. Looks like solr triggering only on update event, does it seem right? @beck24

**Comment by beck24** [comment]
reindex of the entity should trigger on metadata update as well as entity update.
How did you mark them compatible without triggering an update event?

**Comment by Srokap** [comment]
- I went to https://community.elgg.org/plugins/1307052
- clicked on settings for 1.9 release (redirected to https://community.elgg.org/plugins/1307052/releases/1330456/edit)
- Checked 1.10 on the left versions column
- Saved

**Comment by beck24** [comment]
strange, that should definitely trigger an update.  Oh wait - I know why - yes this is a legit bug

The releases aren't indexed, the projects are indexed.  The update was triggered on the release, but the project wasn't reindexed.  I can fix that.

**Comment by beck24** [comment]
Fixed in community_solr repo
