### ISSUE TITLE
Plugin maintenance warning

### ISSUE THREAD

**Issue by teamwebgalli** [Elgg/community_plugins#119]
Seems the plugin maintenance warning is thrown based on the upload date of the last version. Instead of this, it should be based on the last_updated timestamp of the plugin project / release.

For example this plugin is compatible for 1.10 version also. https://community.elgg.org/plugins/384516
But the warning message on that page makes users afraid to use it

**Comment by juho-jaakkola** [comment]
This has already been fixed in #116. Apparently it hasn't been installed to the community yet.

I'll do that now.

**Comment by juho-jaakkola** [comment]
Done. The warnings are gone. :)

**Comment by teamwebgalli** [comment]
Thank you.
