### ISSUE TITLE
Composer intergration

### ISSUE THREAD

**Issue by Wouter0100** [Elgg/community_plugins#137]
Are people interested in this? While talking with @gerard-kanters about the stap where composer-plugins have to manually submit new versions to the Elgg-plugin store, we thought maybe it would be nice to have an intergration with github/bitbucket and Composer.

It could be implemented like:
- Selection box in plugin settings if it's a composer plugin (recommended) or a manually released plugin.
- When manually is selected, the old system is still used.
- When composer is selected, the version history will be received from [packagist.org](https://packagist.org/packages/centillien/follow_tags.json).
  - The zips/tar's could be disabled (or received from git, but that is extra work)
  - When you click the download button, maybe a prompt appears with something in it like `composer require {plugin_name} {version}`, so you're simple able to copy-paste it.
  - Reload of the history (and update) could happen when a webhook is configured in Github/Bitbucket, on this way the `recently updated` still works (instead get latest version every page load, or something).

**Comment by beck24** [comment]
Yeah we've been talking about git integration on and off for a few years now, just nobody has pulled the trigger to get something fully production ready.  There's interest though as the current method is pretty dated.

**Comment by Wouter0100** [comment]
Awesome, in that case I'll take a look in the next couple of days to integrate this :+1:

**Comment by mrclay** [comment]
Sounds good. @hypeJunction Any input here?

**Comment by hypeJunction** [comment]
Check in with Jeroen @jdalsem. He started working on something. I wrote
down some thoughts in another ticket. Will find it later.

**Comment by gerard-kanters** [comment]
I am off course in full support of this. The benefit is that a dev only needs to update the gitb repo and do not need to update the community repo anymore. Zip files can still be available because git has that function anyway, from a user perspective it will be a bit off a hassle, since git adds the branch name to the the zip file . We might be able to overcome this.

While relying more and more on github and composer, it seems like the only logical way.

**Comment by hypeJunction** [comment]
I don't think tying to branches will work. We should check for an actual
github release (or possibly a tag).

**Comment by hypeJunction** [comment]
The main challenge is specifying what Elgg versions are supported by
individual plugin releases. I imagine we have to add custom data to
composer or manifest and parse it. I think we need to add a github
integration that will push webhooks to the community, not sure reverse
integration will work without cron/manual trigger unless we integrate with
github API and query Github on each page request.
I think we should ask Paweł for his thoughts on this, his composer
installer was quite comprehensive and may easily integrate with community
plugins.

**Comment by hypeJunction** [comment]
https://github.com/Elgg/community_plugins/issues/134

**Comment by hypeJunction** [comment]
PR #140

**Comment by jeabakker** [comment]
closing because of dub #134
